=== CaRniFeXeR/cytoflow/FACEJava/resources/schemas/Compensation-ML.v1.0/schema/Compensation-ML.v1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema 
	xmlns="http://www.w3.org/2001/XMLSchema"
	xmlns:comp="http://www.isac-net.org/std/Compensation-ML/v1.0/"
	targetNamespace="http://www.isac-net.org/std/Compensation-ML/v1.0/"
	xmlns:commontypes="http://www.isac-net.org/std/common-types/v1.0/"
	
	elementFormDefault="qualified" attributeFormDefault="qualified"
	version="1.0">
	
	<import namespace="http://www.isac-net.org/std/common-types/v1.0/" schemaLocation="../../common/CommonTypes.v1.0.xsd"/>
	
	<annotation>
		<appinfo source="http://www.flowcyt.org/gating">Compensation Standard</appinfo>
		<documentation xml:lang="en" source="http://www.flowcyt.org/gating">
			version="1.0"
			date="2006-06-13"
			author="Josef Spidlen"
			
			Compensation in Flow Cytometry
			
			Compensation is the process by which the fluorescence "spillover" originating 
			from a fluorochrome other than the one specified for a particular PhotoMultiplier 
			Tube (PMT) detector is subtracted as a percentage of the signal from other PMT’s. 
			
			The inherent overlap of emission spectra from antibody fluorescent labels makes
			compensation necessary. Proper compensation is absolutely crucial for some 
			aspects of flow cytometry, one of which is antigen density measurements.
			
			For more details about compensation refer to 
			http://www.drmr.com/compensation/
			(by to Mario Roederer, latest modification date: May 24, 2000)
			
			This XML Schema is a proposed XML-based standard on a common unambiguous 
			way of describing compensation.

			The work is supported by NIH R01 EB-5034.
		</documentation>
	</annotation>

	<element name="Compensation-ML" type="comp:Compensation-ML">
		<annotation>
			<documentation xml:lang="en">
				The main element of the Compensation-ML XML file.
			</documentation>
		</annotation>
	</element>
	
	<complexType name="Compensation-ML" id="Compensation-ML">
		<annotation>
			<documentation xml:lang="en">
				Contains one or more compensation matrices.
			</documentation>
		</annotation>
		<sequence minOccurs="1" maxOccurs="unbounded">
			<element name="spilloverMatrix" type="comp:SpilloverMatrix" />
		</sequence>
	</complexType>
	
	<complexType name="SpilloverMatrix" id="SpilloverMatrix">
		<annotation>
			<documentation xml:lang="en">
				A compensation matrix for n parameters consists of n spillover elements 
				(rows of the matrix), each of them referencing an FCS attribute by name or 
				by its number within an FCS file. For each spillover element there are n 
				coefficient elements (columns of the matrix). Each coefficient element 
				references an FCS attribute by name or by its number within an FCS file. 
				Another attribute of the coefficient element provides its value that shall be 
				between 0 and 1 (inclusive). 
				
				The name attribute allows for identification of compensation matrices.
				
				In addition to the XML schema validation, a valid compensation matrix 
				is characterized as follows:
				
				1) The compensation matrix shall be a square one, i.e.: 
				 - there shall be the same number of coefficient elements in each spillover element,
				 - and there shall be the same number of coefficient elements per each spillover 
				   element as the number of spillover elements in total.
				
				2) The parameter names are consistent, i.e., the names and order of the parameters 
				   of the coefficient elements is the same for each spillover element and it also 
				   corresponds to the names and order of parameters of the spillover elements 
				   itself (the headings of the rows correspond to the headings of the columns of the matrix).
				
				3) The values on the diagonal of the matrix are 1 (i.e., if the parameter attribute of a 
				  coefficient element equals to the parameter attribute of its parent spillover element then 
				  the value attribute of the coefficient element shall equal to 1).
				
				The semantic of the compensation matrix is as follows:
				
				Let’s have a spillover element S with the parameter attribute X. Let’s have a coordinate 
				element C being a sub-element of S and having parameter attribute Y and value attribute V.
				The semantic of this situation is that V is the amount of X signal in the Y channel for 
				an X-stained cell. V is called the spillover coefficient between X and Y. 
					
				Please note that this is not a reflexive relation, i.e. ,the spillover coefficient between 
				X and Y is not the same as the spillover coefficient between Y and X. 
				
				Please see also example XML documents.
			</documentation>
			
			<!-- 
				TODO
				Describe it more...
			-->
			
		</annotation>
		<sequence minOccurs="1" maxOccurs="unbounded">
			<element name="spillover" type="comp:Spillover" />
		</sequence>
		<attribute name="id" type="ID" use="required"/>
	</complexType>
	
	<complexType name="Spillover" id="Spillover">
		<annotation>
			<documentation xml:lang="en">
				A spillover element corresponds to a row of the compensation matrix.
			</documentation>
		</annotation>
		<sequence minOccurs="1" maxOccurs="unbounded">
			<element name="coefficient" type="comp:Coefficient" />	
		</sequence>
		<attribute name="parameter" type="commontypes:NonEmptyString" use="required" />
	</complexType>
	
	<complexType name="Coefficient" id="Coefficient">
		<annotation>
			<documentation xml:lang="en">
				For each spillover element there are n coefficient elements, one per each column.
			</documentation>
		</annotation>
		<attribute name="parameter" type="commontypes:NonEmptyString" use="required" />
		<attribute name="value" type="commontypes:DoubleBetweenZeroandOne" use="required" />
	</complexType>
	
</schema>

=== CaRniFeXeR/cytoflow/FACEJava/src/org/flowcyt/facejava/compensation/test/files/OneParameterCompensation.xml
<?xml version="1.0" encoding="UTF-8"?>

<comp:Compensation-ML 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:comp="http://www.isac-net.org/std/Compensation-ML/v1.0/"
    xsi:schemaLocation="http://www.isac-net.org/std/Compensation-ML/v1.0/ ../schema/Compensation-ML.v1.0.xsd">
    
    <!-- Let D be the set of parameters in the DataSet and S be the set of parameters in a
         spilloverMatrix.
         
         All the resulting compensators (when applied to the appropriate fcs data set should
         result in 1 parameters being compensated. 
    -->
      
    <!-- 
        FCS File: int-10_events_2_parameters.fcs    	
     	
     	Case: S {proper subset of} D
     	
     	Compensation Matrix:
     	
     	   AS  
     	AS 1.0
     	
     	Compensated Events:
     	(10.0, 20.0)	-> (10.0, 20.0)
		(30.0, 40.0)	-> (30.0, 40.0)
		(50.0, 60.0)	-> (50.0, 60.0)
		(70.0, 80.0)	-> (70.0, 80.0)
		(90.0, 100.0)	-> (90.0, 100.0)
		(110.0, 120.0)	-> (110.0, 120.0)
		(130.0, 140.0)	-> (130.0, 140.0)
		(150.0, 160.0)	-> (150.0, 160.0)
		(170.0, 180.0)	-> (170.0, 180.0)
		(190.0, 200.0)	-> (190.0, 200.0)
    -->
    
    <comp:spilloverMatrix comp:id="S-Sub-D">
        
        <comp:spillover comp:parameter="AS">
            <comp:coefficient comp:parameter="AS" comp:value="1.0"/>
        </comp:spillover>
        
    </comp:spilloverMatrix>
    
    <!-- 
        FCS File: int-10_events_2_parameters.fcs    	
     	
     	Case: D {intersection} S != {empty set} and 
     	      D {not subset of} S and
     	      S {not subset of} D and
     	      |D {intersection} S| = 2
     	
     	Compensation Matrix:
     	
     	   BS  
     	BS 0.987
     	
     	Compensated Events:
     	(10.0, 20.0)	-> (10.0, 20.2634245187437)
		(30.0, 40.0)	-> (30.0, 40.5268490374873)
		(50.0, 60.0)	-> (50.0, 60.790273556231)
		(70.0, 80.0)	-> (70.0, 81.0536980749747)
		(90.0, 100.0)	-> (90.0, 101.317122593718)
		(110.0, 120.0)	-> (110.0, 121.580547112462)
		(130.0, 140.0)	-> (130.0, 141.843971631206)
		(150.0, 160.0)	-> (150.0, 162.107396149949)
		(170.0, 180.0)	-> (170.0, 182.370820668693)
		(190.0, 200.0)	-> (190.0, 202.634245187437)
    -->
    
    <comp:spilloverMatrix comp:id="D-Int-S">

        <comp:spillover comp:parameter="ES">
            <comp:coefficient comp:parameter="DS" comp:value="0.55555"/>
            <comp:coefficient comp:parameter="BS" comp:value="0.66666"/>
            <comp:coefficient comp:parameter="FS" comp:value="0.77777"/>
        </comp:spillover>
        
        <comp:spillover comp:parameter="FS">
            <comp:coefficient comp:parameter="DS" comp:value="0.88888"/>
            <comp:coefficient comp:parameter="BS" comp:value="0.99999"/>
            <comp:coefficient comp:parameter="ES" comp:value="0.10101"/>
        </comp:spillover>
        
        <comp:spillover comp:parameter="DS">
            <comp:coefficient comp:parameter="ES" comp:value="0.33333"/>
            <comp:coefficient comp:parameter="FS" comp:value="0.11111"/>
            <comp:coefficient comp:parameter="BS" comp:value="0.12345"/>
        </comp:spillover>
 
        <comp:spillover comp:parameter="BS">
            <comp:coefficient comp:parameter="ES" comp:value="0.22222"/>
            <comp:coefficient comp:parameter="BS" comp:value="0.987"/>
            <comp:coefficient comp:parameter="FS" comp:value="0.44444"/>
        </comp:spillover>
        
    </comp:spilloverMatrix>
    
</comp:Compensation-ML>

=== CaRniFeXeR/cytoflow/FACEJava/src/org/flowcyt/facejava/compensation/test/files/SingularMatrix.xml
<?xml version="1.0" encoding="UTF-8"?>

<comp:Compensation-ML 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:comp="http://www.isac-net.org/std/Compensation-ML/v1.0/"
    xsi:schemaLocation="http://www.isac-net.org/std/Compensation-ML/v1.0/ ../schema/Compensation-ML.v1.0.xsd">

	<!-- 
        FCS File: int-10_events_8_parameters.fcs    	
     	
     	Compensation Matrix:
     	
     	   BS   CS   DS   ES   GS   HS
     	BS 0.1  0.2  0.3  0.4  0.5  0.6
     	CS 0.7  0.8  0.9  0.10 0.11 0.12
     	DS 0.13 0.14 0.15 0.16 0.17 0.18
     	ES 0.19 0.20 0.21 0.22 0.23 0.24
     	GS 0.25 0.26 0.27 0.28 0.29 0.30
     	HS 0.31 0.32 0.33 0.34 0.35 0.36
     	
     	Compensation Matrix in Echelon Form:
     	
     	   BS CS DS ES GS   HS
     	BS 1  0  -1 0  -0.8 -1.6
        CS 0  1  2  0  0.7  1.4
        DS 0  0  0  1  1.1  1.2
        ES 0  0  0  0  0    0
        GS 0  0  0  0  0    0
        HS 0  0  0  0  0    0
        
        Clearly, it's singular and non-invertible
     	
    -->
    
    <comp:spilloverMatrix comp:id="Singular">

        <comp:spillover comp:parameter="BS">
        	<comp:coefficient comp:parameter="BS" comp:value="0.1"/>
            <comp:coefficient comp:parameter="CS" comp:value="0.2"/>
            <comp:coefficient comp:parameter="DS" comp:value="0.3"/>
            <comp:coefficient comp:parameter="ES" comp:value="0.4"/>
            <comp:coefficient comp:parameter="GS" comp:value="0.5"/>
            <comp:coefficient comp:parameter="HS" comp:value="0.6"/>
            <comp:coefficient comp:parameter="JS" comp:value="0.00001"/>
            <comp:coefficient comp:parameter="KS" comp:value="0.00002"/>
            <comp:coefficient comp:parameter="LS" comp:value="0.00003"/>
        </comp:spillover>
        
        <comp:spillover comp:parameter="CS">
            <comp:coefficient comp:parameter="BS" comp:value="0.7"/>
            <comp:coefficient comp:parameter="CS" comp:value="0.8"/>
            <comp:coefficient comp:parameter="DS" comp:value="0.9"/>
            <comp:coefficient comp:parameter="ES" comp:value="0.10"/>
            <comp:coefficient comp:parameter="GS" comp:value="0.11"/>
            <comp:coefficient comp:parameter="HS" comp:value="0.12"/>
            <comp:coefficient comp:parameter="JS" comp:value="0.00004"/>
            <comp:coefficient comp:parameter="KS" comp:value="0.00005"/>
            <comp:coefficient comp:parameter="LS" comp:value="0.00006"/>
        </comp:spillover>
        
        <comp:spillover comp:parameter="DS">
            <comp:coefficient comp:parameter="BS" comp:value="0.13"/>
            <comp:coefficient comp:parameter="CS" comp:value="0.14"/>
            <comp:coefficient comp:parameter="DS" comp:value="0.15"/>
            <comp:coefficient comp:parameter="ES" comp:value="0.16"/>
            <comp:coefficient comp:parameter="GS" comp:value="0.17"/>
            <comp:coefficient comp:parameter="HS" comp:value="0.18"/>
            <comp:coefficient comp:parameter="JS" comp:value="0.00007"/>
            <comp:coefficient comp:parameter="KS" comp:value="0.00008"/>
            <comp:coefficient comp:parameter="LS" comp:value="0.00009"/>
        </comp:spillover>
 
        <comp:spillover comp:parameter="ES">
            <comp:coefficient comp:parameter="BS" comp:value="0.19"/>
            <comp:coefficient comp:parameter="CS" comp:value="0.20"/>
            <comp:coefficient comp:parameter="DS" comp:value="0.21"/>
            <comp:coefficient comp:parameter="ES" comp:value="0.22"/>
            <comp:coefficient comp:parameter="GS" comp:value="0.23"/>
            <comp:coefficient comp:parameter="HS" comp:value="0.24"/>
            <comp:coefficient comp:parameter="JS" comp:value="0.000010"/>
            <comp:coefficient comp:parameter="KS" comp:value="0.000011"/>
            <comp:coefficient comp:parameter="LS" comp:value="0.000012"/>
        </comp:spillover>
        
        <comp:spillover comp:parameter="GS">
            <comp:coefficient comp:parameter="BS" comp:value="0.25"/>
            <comp:coefficient comp:parameter="CS" comp:value="0.26"/>
            <comp:coefficient comp:parameter="DS" comp:value="0.27"/>
            <comp:coefficient comp:parameter="ES" comp:value="0.28"/>
            <comp:coefficient comp:parameter="GS" comp:value="0.29"/>
            <comp:coefficient comp:parameter="HS" comp:value="0.30"/>
            <comp:coefficient comp:parameter="JS" comp:value="0.000013"/>
            <comp:coefficient comp:parameter="KS" comp:value="0.000014"/>
            <comp:coefficient comp:parameter="LS" comp:value="0.000015"/>
        </comp:spillover>
 
        <comp:spillover comp:parameter="HS">
            <comp:coefficient comp:parameter="BS" comp:value="0.31"/>
            <comp:coefficient comp:parameter="CS" comp:value="0.32"/>
            <comp:coefficient comp:parameter="DS" comp:value="0.33"/>
            <comp:coefficient comp:parameter="ES" comp:value="0.34"/>
            <comp:coefficient comp:parameter="GS" comp:value="0.35"/>
            <comp:coefficient comp:parameter="HS" comp:value="0.36"/>
            <comp:coefficient comp:parameter="JS" comp:value="0.000016"/>
            <comp:coefficient comp:parameter="KS" comp:value="0.000017"/>
            <comp:coefficient comp:parameter="LS" comp:value="0.000018"/>
        </comp:spillover>
        
        <comp:spillover comp:parameter="JS">
            <comp:coefficient comp:parameter="BS" comp:value="0.37"/>
            <comp:coefficient comp:parameter="CS" comp:value="0.38"/>
            <comp:coefficient comp:parameter="DS" comp:value="0.39"/>
            <comp:coefficient comp:parameter="ES" comp:value="0.40"/>
            <comp:coefficient comp:parameter="GS" comp:value="0.41"/>
            <comp:coefficient comp:parameter="HS" comp:value="0.42"/>
            <comp:coefficient comp:parameter="JS" comp:value="0.000019"/>
            <comp:coefficient comp:parameter="KS" comp:value="0.000020"/>
            <comp:coefficient comp:parameter="LS" comp:value="0.000021"/>
        </comp:spillover>
        
        <comp:spillover comp:parameter="KS">
            <comp:coefficient comp:parameter="BS" comp:value="0.43"/>
            <comp:coefficient comp:parameter="CS" comp:value="0.44"/>
            <comp:coefficient comp:parameter="DS" comp:value="0.45"/>
            <comp:coefficient comp:parameter="ES" comp:value="0.46"/>
            <comp:coefficient comp:parameter="GS" comp:value="0.47"/>
            <comp:coefficient comp:parameter="HS" comp:value="0.48"/>
            <comp:coefficient comp:parameter="JS" comp:value="0.000022"/>
            <comp:coefficient comp:parameter="KS" comp:value="0.000023"/>
            <comp:coefficient comp:parameter="LS" comp:value="0.000024"/>
        </comp:spillover>
        
        <comp:spillover comp:parameter="LS">
            <comp:coefficient comp:parameter="BS" comp:value="0.49"/>
            <comp:coefficient comp:parameter="CS" comp:value="0.50"/>
            <comp:coefficient comp:parameter="DS" comp:value="0.51"/>
            <comp:coefficient comp:parameter="ES" comp:value="0.52"/>
            <comp:coefficient comp:parameter="GS" comp:value="0.53"/>
            <comp:coefficient comp:parameter="HS" comp:value="0.54"/>
            <comp:coefficient comp:parameter="JS" comp:value="0.000025"/>
            <comp:coefficient comp:parameter="KS" comp:value="0.000026"/>
            <comp:coefficient comp:parameter="LS" comp:value="0.000027"/>
        </comp:spillover>
        
    </comp:spilloverMatrix>
   
</comp:Compensation-ML>

=== CaRniFeXeR/cytoflow/FACEJava/src/org/flowcyt/facejava/compensation/test/files/DuplicateIds.xml
<?xml version="1.0" encoding="UTF-8"?>

<comp:Compensation-ML 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:comp="http://www.isac-net.org/std/Compensation-ML/v1.0/"
    xsi:schemaLocation="http://www.isac-net.org/std/Compensation-ML/v1.0/ ../schema/Compensation-ML.v1.0.xsd">
    
    <!-- Duplicate Ids -->
    
    <comp:spilloverMatrix comp:id="Fluor-PhyEry-Cy5PE-Compensation">
      
        <comp:spillover comp:parameter="Fluor">
            <comp:coefficient comp:parameter="PhyEry" comp:value="0.16501"/>
            <comp:coefficient comp:parameter="Cy5PE" comp:value="0.03457"/>
        </comp:spillover>
 
        <comp:spillover comp:parameter="PhyEry">
            <comp:coefficient comp:parameter="Fluor" comp:value="0.01454"/>
            <comp:coefficient comp:parameter="Cy5PE" comp:value="0.21343"/>
        </comp:spillover>
        
        <comp:spillover comp:parameter="Cy5PE">
            <comp:coefficient comp:parameter="Fluor" comp:value="0.0059"/>
            <comp:coefficient comp:parameter="PhyEry" comp:value="0.23623"/>
        </comp:spillover>
        
    </comp:spilloverMatrix>
    
    <comp:spilloverMatrix comp:id="Fluor-PhyEry-Cy5PE-Compensation">
        
        <comp:spillover comp:parameter="FITC">
            <comp:coefficient comp:parameter="FITC" comp:value="1"/>
            <comp:coefficient comp:parameter="PE" comp:value="0.15"/>
        </comp:spillover>
        
        <comp:spillover comp:parameter="PE">
            <comp:coefficient comp:parameter="FITC" comp:value="0.01"/>
            <comp:coefficient comp:parameter="PE" comp:value="1"/>
        </comp:spillover>
        
    </comp:spilloverMatrix>
    
    
</comp:Compensation-ML>

=== CaRniFeXeR/cytoflow/FACEJava/src/org/flowcyt/facejava/compensation/test/files/SpilloverMatrixValueTest.xml
<?xml version="1.0" encoding="UTF-8"?>

<comp:Compensation-ML 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:comp="http://www.isac-net.org/std/Compensation-ML/v1.0/"
    xsi:schemaLocation="http://www.isac-net.org/std/Compensation-ML/v1.0/ ../schema/Compensation-ML.v1.0.xsd">
    
    <!--  
    	With this matrix we'll test that we retrieve values correctly with all versions
    	of parameters X and Y when none, one or both are specified in the spilloverMatrix, and
    	when X = Y and X != Y.
    
    	Test Cases:
    	
    	Spillover Parameter		Coefficient Parameter		Expected Value
    	
    	NotSpecified1			NotSpecified2				0
    	NotSpecified1			Fluor						0
    	Cy5PE					NotSpecified2				0
    	Cy5PE					Cy5PE						1
    	NotSpecified1			NotSpecified1				1
    	Fluor					Cy5PE						0.03457
    	Fluor					Fluor						0.9876
    	PhyEry					Cy5PE						0.21343  \...(A single test that they're not equal)
    	Cy5PE					PhyEry						0.23623  /

    -->
    
    <comp:spilloverMatrix comp:id="BasicTestMatrix">
      
        <comp:spillover comp:parameter="Fluor">
	        <comp:coefficient comp:parameter="Fluor" comp:value="0.9876"/>
            <comp:coefficient comp:parameter="PhyEry" comp:value="0.16501"/>
            <comp:coefficient comp:parameter="Cy5PE" comp:value="0.03457"/>
        </comp:spillover>
 
        <comp:spillover comp:parameter="PhyEry">
            <comp:coefficient comp:parameter="Fluor" comp:value="0.01454"/>
            <comp:coefficient comp:parameter="Cy5PE" comp:value="0.21343"/>
        </comp:spillover>
        
        <comp:spillover comp:parameter="Cy5PE">
            <comp:coefficient comp:parameter="Fluor" comp:value="0.0059"/>
            <comp:coefficient comp:parameter="PhyEry" comp:value="0.23623"/>
        </comp:spillover>
        
    </comp:spilloverMatrix>
    
    <!-- 
    	With this matrix we'll test the behaviour when multiple values for the same parameter
    	name(s) are specified. The last specified value between two parameters (in the same order)
    	is used.
    
    	Spillover Parameter		Coefficient Parameter		Expected Value
    	Fluor					PhyEry						0.44444
    	PhyEry					Fluor						0.66666
    	Cy5PE					Cy5PE						0.88888
    -->
    
    <comp:spilloverMatrix comp:id="MultipleValuesSpecifiedMatrix">
      
        <comp:spillover comp:parameter="Fluor">
	        <comp:coefficient comp:parameter="PhyEry" comp:value="0.16501"/>
            <comp:coefficient comp:parameter="Cy5PE" comp:value="0.03457"/>
        </comp:spillover>
 
        <comp:spillover comp:parameter="PhyEry">
            <comp:coefficient comp:parameter="Fluor" comp:value="0.01454"/>
            <comp:coefficient comp:parameter="Cy5PE" comp:value="0.21343"/>
            <comp:coefficient comp:parameter="Fluor" comp:value="0.11111"/>
            <comp:coefficient comp:parameter="Fluor" comp:value="0.22222"/>
            <comp:coefficient comp:parameter="Fluor" comp:value="0.33333"/>
            <comp:coefficient comp:parameter="FL111" comp:value="0.01454"/>
            <comp:coefficient comp:parameter="Fluor" comp:value="0.44444"/>
            <comp:coefficient comp:parameter="FL222" comp:value="0.21343"/>
            <comp:coefficient comp:parameter="Fluor" comp:value="0.55555"/>
            <comp:coefficient comp:parameter="FL333" comp:value="0.21343"/>
            <comp:coefficient comp:parameter="Fluor" comp:value="0.66666"/>
        </comp:spillover>
        
        <comp:spillover comp:parameter="Fluor">
	        <comp:coefficient comp:parameter="PhyEry" comp:value="0.22222"/>
	    </comp:spillover>
        
        <comp:spillover comp:parameter="Cy5PE">
            <comp:coefficient comp:parameter="Fluor" comp:value="0.0059"/>
            <comp:coefficient comp:parameter="Cy5PE" comp:value="0.11111"/>
            <comp:coefficient comp:parameter="PhyEry" comp:value="0.23623"/>
            <comp:coefficient comp:parameter="Cy5PE" comp:value="0.22222"/>
        </comp:spillover>
        
        <comp:spillover comp:parameter="FL111">
        	<comp:coefficient comp:parameter="Fluor" comp:value="0.0059"/>
            <comp:coefficient comp:parameter="Cy5PE" comp:value="0.11111"/>
        </comp:spillover>
        
        <comp:spillover comp:parameter="Fluor">
        	<comp:coefficient comp:parameter="FL111" comp:value="0.01454"/>
            <comp:coefficient comp:parameter="FL222" comp:value="0.21343"/>
            <comp:coefficient comp:parameter="FL333" comp:value="0.21343"/>
	        <comp:coefficient comp:parameter="PhyEry" comp:value="0.44444"/>
	    </comp:spillover>
        
        <comp:spillover comp:parameter="Cy5PE">
            <comp:coefficient comp:parameter="Cy5PE" comp:value="0.33333"/>
            <comp:coefficient comp:parameter="Cy5PE" comp:value="0.44444"/>
            <comp:coefficient comp:parameter="Cy5PE" comp:value="0.55555"/>
            <comp:coefficient comp:parameter="Cy5PE" comp:value="0.66666"/>
            <comp:coefficient comp:parameter="Cy5PE" comp:value="0.77777"/>
            <comp:coefficient comp:parameter="Cy5PE" comp:value="0.88888"/>
        </comp:spillover>
        
    </comp:spilloverMatrix>   
    
</comp:Compensation-ML>
